export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_VAL = "INCREMENT_VAL";
export const DECREMENT_VAL = "DECREMENT_VAL";
export const STORE_RESULT = "STORE_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";
